# Generated by Django 3.1 on 2020-08-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200813_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='simpletask',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
