# Generated by Django 3.1 on 2020-08-18 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_simpletask_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletask',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 15, 6, 41, 364849)),
        ),
    ]
