# Generated by Django 3.1 on 2020-08-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200818_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simpletask',
            name='creation',
            field=models.DateTimeField(default=None),
        ),
    ]
