# Generated by Django 3.1 on 2020-08-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200818_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='due_date_clean_display',
            field=models.DateField(null=True),
        ),
    ]
