# Generated by Django 3.1 on 2020-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_simpletask_due_date_clean_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletask',
            name='due_date_clean_display',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
