# Generated by Django 3.1 on 2020-08-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200819_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpletask',
            name='due_date_clean_display',
        ),
    ]
