# Generated by Django 3.1 on 2020-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_tasklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='name',
            field=models.CharField(default='Sans nom', max_length=25, null=True),
        ),
    ]
