# Generated by Django 3.1 on 2020-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20200821_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='couleur',
            field=models.CharField(default='#21756b', max_length=7),
        ),
    ]
