# Generated by Django 3.1 on 2020-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20200824_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='is_important',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simpletask',
            name='is_urgent',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
