# Generated by Django 3.1 on 2020-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_simpletask_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletask',
            name='in_progress',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
